(part "TORX1950A_F_"
    (packageRef "TORX1950AF")
    (interface
        (port "1" (symbPinId 1) (portName "OUTPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VCC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND2") (portType INOUT))
        (port "MH1" (symbPinId 5) (portName "CASE_1") (portType INOUT))
        (port "MH2" (symbPinId 6) (portName "CASE_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Toshiba")
    (property "Manufacturer_Part_Number" "TORX1950A(F)")
    (property "Mouser_Part_Number" "71-TORX1950A(F)")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Toshiba/TORX1950AF?qs=gev7jUp%252BQ%252BhPDbv%252Bwuk0PA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Optical Receiver 10Mbps Single 50m 6-Pin )")
    (property "Datasheet_Link" "https://toshiba.semicon-storage.com/info/TORX1950A(F)_datasheet_en_20160418.pdf?did=45664&prodName=TORX1950A(F)")
    (property "symbolName1" "TORX1950A_F_")
)
