(part "PJ-037A"
    (packageRef "PJ037A")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "PJ-037A")
    (property "Mouser_Part_Number" "490-PJ-037A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/PJ-037A?qs=WyjlAZoYn53bdNRXfildEA%3D%3D")
    (property "Arrow_Part_Number" "PJ-037A")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/pj-037a/cui-devices?utm_currency=USD&region=nac")
    (property "Description" "PJ-037A - 2.0 x 6.5 mm, 2.5 A, Horizontal, Through Hole, Dc Power Jack Connector")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/PJ-037A.pdf")
    (property "symbolName1" "PJ-037A")
)
