(part "ASDLJ-E-45_1584MHz-L-R-T"
    (packageRef "ASDLJE451584MHzLRT")
    (interface
        (port "1" (symbPinId 1) (portName "OE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ASDLJ-E-45.1584MHz-L-R-T")
    (property "Mouser_Part_Number" "815-ASDLJE451584MLRT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ASDLJ-E-45.1584MHz-L-R-T?qs=wT7LY0lnAe3sHOZDDuH%252Bxw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "45.1584 MHz XO (Standard) CMOS Oscillator 3.3V Enable/Disable 4-SMD, No Lead")
    (property "Datasheet_Link" "https://www.digikey.ph/en/products/detail/abracon-llc/ASDLJ-E-45-1584MHZ-L-R-T/24387249")
    (property "symbolName1" "ASDLJ-E-45_1584MHz-L-R-T")
)
