(part "TPS7A3301RGWR"
    (packageRef "QFN65P500X500X100-21N-D")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_4") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_5") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_6") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NC_7") (portType INOUT))
        (port "11" (symbPinId 11) (portName "NC_8") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NC_9") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EN") (portType INOUT))
        (port "14" (symbPinId 14) (portName "NR/SS") (portType INOUT))
        (port "15" (symbPinId 15) (portName "IN_1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "IN_2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "NC_10") (portType INOUT))
        (port "18" (symbPinId 18) (portName "NC_11") (portType INOUT))
        (port "19" (symbPinId 19) (portName "NC_12") (portType INOUT))
        (port "20" (symbPinId 20) (portName "OUT_2") (portType INOUT))
        (port "21" (symbPinId 21) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7A3301RGWR")
    (property "Mouser_Part_Number" "595-TPS7A3301RGWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7A3301RGWR?qs=i8JZjLRTtkLEU7%252B8PZb5ZA%3D%3D")
    (property "Arrow_Part_Number" "TPS7A3301RGWR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps7a3301rgwr/texas-instruments?region=nac")
    (property "Description" "-3V to -36V Vin, 1A output current, ultra-low-noise, high-PSRR, low-dropout (LDO) linear regulator")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tps7a33.pdf")
    (property "symbolName1" "TPS7A3301RGWR")
)
