(part "TPA6120A2DWPR"
    (packageRef "SOIC127P1040X275-21N")
    (interface
        (port "1" (symbPinId 1) (portName "LVCC-") (portType INOUT))
        (port "2" (symbPinId 2) (portName "LOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "LVCC+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "LIN+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "LIN-") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_3") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_4") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NC_5") (portType INOUT))
        (port "11" (symbPinId 11) (portName "NC_6") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NC_7") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC_8") (portType INOUT))
        (port "14" (symbPinId 14) (portName "NC_9") (portType INOUT))
        (port "15" (symbPinId 15) (portName "NC_10") (portType INOUT))
        (port "16" (symbPinId 16) (portName "RIN-") (portType INOUT))
        (port "17" (symbPinId 17) (portName "RIN+") (portType INOUT))
        (port "18" (symbPinId 18) (portName "RVCC+") (portType INOUT))
        (port "19" (symbPinId 19) (portName "ROUT") (portType INOUT))
        (port "20" (symbPinId 20) (portName "RVCC-") (portType INOUT))
        (port "21" (symbPinId 21) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPA6120A2DWPR")
    (property "Mouser_Part_Number" "595-TPA6120A2DWPR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPA6120A2DWPR?qs=ojKcPFmCWSXiGd7G5JhN2A%3D%3D")
    (property "Arrow_Part_Number" "TPA6120A2DWPR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tpa6120a2dwpr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Audio Amplifiers High Fidelity Stereo Headphone Drv")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tpa6120a2.pdf")
    (property "symbolName1" "TPA6120A2DWPR")
)
