(part "OPA1612AIDRGR"
    (packageRef "SON50P300X300X80-9N-D")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V+") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA1612AIDRGR")
    (property "Mouser_Part_Number" "595-OPA1612AIDRGR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA1612AIDRGR?qs=m1T3c8F5IUKK0sm07a9upg%3D%3D")
    (property "Arrow_Part_Number" "OPA1612AIDRGR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/opa1612aidrgr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "SoundPlus Audio Operational Amplifier with 1.1nV/Hz Noise, Low THD and Precision")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/opa1612.pdf")
    (property "symbolName1" "OPA1612AIDRGR")
)
