(part "216700-0249"
    (packageRef "2167000249")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "15") (portType INOUT))
        (port "16" (symbPinId 16) (portName "16") (portType INOUT))
        (port "17" (symbPinId 17) (portName "17") (portType INOUT))
        (port "18" (symbPinId 18) (portName "18") (portType INOUT))
        (port "19" (symbPinId 19) (portName "19") (portType INOUT))
        (port "20" (symbPinId 20) (portName "20") (portType INOUT))
        (port "21" (symbPinId 21) (portName "21") (portType INOUT))
        (port "22" (symbPinId 22) (portName "22") (portType INOUT))
        (port "23" (symbPinId 23) (portName "23") (portType INOUT))
        (port "24" (symbPinId 24) (portName "24") (portType INOUT))
        (port "25" (symbPinId 25) (portName "MP_1") (portType INOUT))
        (port "26" (symbPinId 26) (portName "MP_2") (portType INOUT))
        (port "27" (symbPinId 27) (portName "MP_3") (portType INOUT))
        (port "28" (symbPinId 28) (portName "MP_4") (portType INOUT))
        (port "29" (symbPinId 29) (portName "MP_5") (portType INOUT))
        (port "30" (symbPinId 30) (portName "MP_6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "216700-0249")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Board to Board & Mezzanine Connectors Board-to-Board Recept 0.35mm Pitch  0.60mm Mated Hght 1.90mm Mated Width 24 Ckts")
    (property "Datasheet_Link" "https://www.molex.com/content/dam/molex/molex-dot-com/products/automated/en-us/salesdrawingpdf/216/216700/2167000249_sd.pdf")
    (property "symbolName1" "216700-0249")
)
