(part "ASDLJ-E-49_152MHZ-L-R-T"
    (packageRef "ASDLJE49152MHZLRT")
    (interface
        (port "1" (symbPinId 1) (portName "OE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ASDLJ-E-49.152MHZ-L-R-T")
    (property "Mouser_Part_Number" "815-ASDLJE49152MHLRT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ASDLJ-E-49.152MHz-L-R-T?qs=wT7LY0lnAe3ZSqewNL8EtA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "49.152 MHz XO (Standard) CMOS Oscillator 3.3V Enable/Disable 4-SMD, No Lead")
    (property "Datasheet_Link" "https://abracon.com/datasheets/ASDLJ.pdf")
    (property "symbolName1" "ASDLJ-E-49_152MHZ-L-R-T")
)
